apiVersion: v1
kind: Pod
metadata:
  name: node-preferred2
  labels:
    app: node-affinity-pod
spec:
  containers:
  - name: test-pod01
    image: wangyanglinux/myapp:v1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io
            operator: In
            values:
            - node03
#            - node04
