apiVersion: v1
kind: Pod
metadata:
  name: node-required
  labels:
    app: node-affinity-pod
spec:
  containers:
  - name: test-pod01
    image: wangyanglinux/myapp:v1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io
            operator: NotIn
            values:
            - node02
