apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp01
        image: wangyanglinux/myapp:v1
        ports:
        - containerPort: 80
