apiVersion: v1
kind: Pod
metadata:
  name: live-port-pod
spec:
  containers:
  - name: live-port-container
    image: wangyanglinux/myapp:v1
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 3
      tcpSocket:
        port: 8080
