apiVersion: v1
kind: Pod
metadata:
  name: start-stop-pod
spec:
  containers:
  - name: start-stop-container
    image: wangyanglinux/myapp:v1
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo Hello from the PostStart handler > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh","-c","echo Hello from the poststop handler > /usr/share/message"]
