apiVersion: v1
kind: Pod
metadata:
  name: test-pod03
spec:
  containers:
  - image: wangyanglinux/myapp:v1
    name: test-container01
    volumeMounts:
    - mountPath: /test
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory
